name: Isolated Static check

on:
  pull_request:
    paths:
      - "ruff-requirements.txt"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  Ruff-format:
    name: Validate formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r ruff-requirements.txt
      - name: Check code style with ruff
        run: |
          ruff format --check .

  Ruff:
    name: Check with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade -r ruff-requirements.txt
      - name: Lint with ruff
        run: |
          ruff check --output-format github .

  PyLint:
    name: Check with pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Ubuntu dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y python3-dev python3-gi python3-gi-cairo
          sudo apt-get install -y gobject-introspection libgirepository-2.0-dev libcairo2-dev
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test_requirements.txt PyGObject
          pip install --upgrade -r pylint-requirements.txt
      - name: Install package for test
        run: pip install -e .
      - name: Lint with pylint
        run: pylint --output-format=github urwid
